dependencies:
  - nbserverproxy
  - conda-forge::altair
  - conda-forge::plotly
  - pyviz/label/dev::holoviews=1.11.0a10
  - pyviz/label/dev::hvplot=0.3.0a5
  - pyviz/label/dev::panel=0.2.0a8
  - pyviz::param=1.8.1
  - pyviz::pyviz_comms=0.6.0
  - bokeh::bokeh
